version: '3'
services:
  springboot:
    image: springboot:1.0
    container_name: springboot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "9000:8080"
