#服务器
server:
  port: 80
  servlet:
    context-path: /

#配置日志
logging:
  file: log\text.log
  level:
    root: info

spring:
  application:
    name: springboot
  #redis
  redis:
    host: localhost
    port: 6379
  #thymeleaf模板引擎
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  #热部署
  devtools:
    restart:
      enabled: true
      exclude: /static/**,/templates/**
  #数据库
  datasource:
    url: jdbc:mysql://localhost:8066/wangjiayu?characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #es
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: wangjiayu
      repositories:
        enabled: true

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#mybatis分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
