server:
  port: 8080

logging:
  file: /log/springboot.log
  level:
    root: info

spring:
  application:
    name: springboot
#  rabbitmq:
#    host: 192.168.31.175
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    publisher-confirms: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  datasource:
    #这里采用内网通信访问其他容器应用  容器名称:容器端口 <==> ip:宿主机端口
    url: jdbc:mysql://mysql2:3306/test?characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
