#服务器
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30

#配置日志
logging:
  file: log\text.log
  level:
    root: info

spring:
  #redis
  redis:
    host: localhost
    port: 6379
  #rabbitmq
  application:
    name: springboot
  #thymeleaf模板引擎
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  #热部署
  devtools:
    restart:
      enabled: true
      exclude: /static/**,/templates/**
  #数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#mybatis分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
    
