server:
  port: 8080
  servlet:
    context-path: /

logging:
  file: c:\log\springboot.txt
  level:
    root: info

spring:
  application:
    name: springboot
  rabbitmq:
    host: 192.168.31.175
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
  redis:
    database: 0
    host: 192.168.31.175
    port: 6379
    password: 123
  datasource:
    url: jdbc:mysql://192.168.31.175:3306/test?characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
